import { infiniteQueryOptions, queryOptions } from '@tanstack/react-query';
import { z } from 'zod';
import { apiClient, readJson } from '@/app/api-client';
import { DISCOVER_INITIAL_PAGE_SIZE, discoveryCapabilitiesSchema, discoveryPageSchema, discoveryVolumeSchema } from './-discovery.types';
import type { BrowseFilters, DiscoveryCapabilities, DiscoveryPage, DiscoverySection, DiscoveryType, DiscoveryVolume } from './-discovery.types';

const discoveryItemsSchema = z.array(z.record(z.unknown()));
export function discoveryCapabilitiesQueryOptions(section: DiscoverySection) { return queryOptions({ queryKey: ['discovery', 'capabilities', section], queryFn: () => apiClient.get('discovery/capabilities', { searchParams: { section } }).then(res => readJson(res, discoveryCapabilitiesSchema)) as Promise<DiscoveryCapabilities>, staleTime: 30 * 60_000 }); }
function canonicalDiscoveryType(type: DiscoveryType): DiscoveryType { return type === 'new' ? 'recently-started' : (type === 'upcoming' || type === 'upcoming-launches') ? 'upcoming-launches' : (type === 'trending' || type === 'recently-active') ? 'recently-active' : type; }
export function discoveryVolumeQueryOptions(type: DiscoveryType, section: DiscoverySection) { const requestType = canonicalDiscoveryType(type); return queryOptions({ queryKey: ['discovery', requestType, section], queryFn: () => apiClient.get('discovery', { searchParams: { type: requestType, section } }).then(res => readJson(res, discoveryItemsSchema)).then(items => items.map(item => normalizeDiscoveryItem(item, requestType))), staleTime: 5 * 60_000, refetchOnMount: false }); }
export async function fetchDiscoveryVolumePage(type: DiscoveryType, section: DiscoverySection, offset: number | string, limit = DISCOVER_INITIAL_PAGE_SIZE, excludeAdded = false): Promise<DiscoveryPage> { const requestType = canonicalDiscoveryType(type); const cursor = typeof offset === 'string' ? offset : ''; const response = await apiClient.get('discovery', { searchParams: { type: requestType, section, paginated: 'true', offset: typeof offset === 'number' ? String(offset) : '0', ...(cursor ? { cursor } : {}), limit: String(limit), ...(excludeAdded ? { exclude_added: 'true' } : {}) }, timeout: 60_000 }); const page = await readJson(response, discoveryPageSchema); return normalizeDiscoveryPage(page, requestType); }
export function discoveryShelfQueryOptions(type: DiscoveryType, section: DiscoverySection, limit = 12, excludeAdded = false) { const requestType = canonicalDiscoveryType(type); return queryOptions({ queryKey: ['discovery', 'shelf', requestType, section, limit, excludeAdded], queryFn: () => fetchDiscoveryVolumePage(requestType, section, 0, limit, excludeAdded), staleTime: 5 * 60_000, refetchOnMount: false }); }
export async function refreshDiscoveryFacts(): Promise<{ sync_task_id: number | null; coverage: string; source_note?: string }> { const response = await apiClient.post('discovery/facts/refresh'); return readJson(response) as Promise<{ sync_task_id: number | null; coverage: string; source_note?: string }>; }
export function discoveryShelfInfiniteQueryOptions(type: DiscoveryType, section: DiscoverySection, limit = DISCOVER_INITIAL_PAGE_SIZE) { return infiniteQueryOptions({ queryKey: ['discovery', 'shelf', type, section, limit], initialPageParam: 0 as number | string, queryFn: ({ pageParam }) => fetchDiscoveryVolumePage(type, section, pageParam as number | string, limit), getNextPageParam: (lastPage) => (lastPage.has_more ?? (lastPage.total != null && lastPage.offset + lastPage.items.length < lastPage.total)) ? lastPage.next_cursor ?? lastPage.next_offset ?? lastPage.offset + lastPage.page_size : undefined, staleTime: 5 * 60_000, refetchOnMount: false }); }
export function browseDiscoveryQueryOptions(filters: BrowseFilters, limit = DISCOVER_INITIAL_PAGE_SIZE) { return infiniteQueryOptions({ queryKey: ['discovery', 'browse', filters, limit], initialPageParam: 0 as number | string, queryFn: ({ pageParam }) => fetchBrowseDiscoveryPage(filters, pageParam as number | string, limit), getNextPageParam: (lastPage) => (lastPage.has_more ?? (lastPage.total != null && lastPage.offset + lastPage.items.length < lastPage.total)) ? lastPage.next_cursor ?? lastPage.next_offset ?? lastPage.offset + lastPage.page_size : undefined, staleTime: 5 * 60_000, refetchOnMount: false }); }
export async function fetchBrowseDiscoveryPage(filters: BrowseFilters, offset: number | string, limit = DISCOVER_INITIAL_PAGE_SIZE): Promise<DiscoveryPage> { const cursor = typeof offset === 'string' ? offset : ''; const searchParams: Record<string, string> = { section: filters.section, offset: typeof offset === 'number' ? String(offset) : '0', ...(cursor ? { cursor } : {}), limit: String(limit), sort: filters.sort }; if (filters.hide_added) searchParams.exclude_added = 'true'; for (const key of ['q', 'publisher', 'decade', 'character', 'genre', 'status', 'tags', 'demographic', 'original_language', 'year', 'author', 'artist', 'content_rating'] as const) { const value = filters[key]; if (value) searchParams[key] = value; } const response = await apiClient.get('discovery/browse', { searchParams, timeout: 60_000 }); const page = await readJson(response, discoveryPageSchema); return normalizeDiscoveryPage(page, filters.section === 'manga' ? 'recently-updated' : 'trending'); }
function normalizeDiscoveryPage(page: z.infer<typeof discoveryPageSchema>, type: DiscoveryType): DiscoveryPage { return { ...page, has_more: page.has_more ?? (page.total != null && page.offset + page.items.length < page.total), items: page.items.map(item => normalizeDiscoveryItem(item, type)) }; }
export function normalizeDiscoveryItem(item: Record<string, unknown>, type: DiscoveryType): DiscoveryVolume { const normalized = (type === 'upcoming' || type === 'upcoming-launches') ? { ...item, comicvine_id: item.volume_id ?? item.comicvine_id, metadata_source: item.metadata_source ?? 'comicvine', metadata_id: item.metadata_id ?? String(item.volume_id ?? item.comicvine_id ?? ''), title: item.volume_title || item.title || '', already_added: item.already_added ?? null, id: item.issue_id, status: item.status ?? 'Launch' } : { ...item, metadata_source: item.metadata_source ?? 'comicvine', metadata_id: item.metadata_id ?? String(item.comicvine_id ?? ''), title: item.title || '', already_added: item.already_added ?? null, status: item.status ?? ((type === 'trending' || type === 'recently-active') ? 'Recently active' : undefined) }; return discoveryVolumeSchema.parse(normalized); }
